package com.pxbtdev.model.entity;

import lombok.Builder;
import lombok.Data;

import java.util.List;

@Data
@Builder
public class TestCase {
    private String id;
    private String title;
    private String description;
    private String precondition;
    private List<String> steps;
    private List<String> expectedResults;
    private String priority; // High, Medium, Low
    private List<String> tags;

    public String toHumanReadableFormat() {
        StringBuilder sb = new StringBuilder();

        sb.append("Test Case: ").append(title).append("\n");
        sb.append("ID: ").append(id).append("\n");
        sb.append("Priority: ").append(priority).append("\n");
        sb.append("Tags: ").append(String.join(", ", tags)).append("\n\n");

        sb.append("Description:\n").append(description).append("\n\n");

        sb.append("Precondition:\n").append(precondition).append("\n\n");

        sb.append("Steps:\n");
        for (int i = 0; i < steps.size(); i++) {
            sb.append(i + 1).append(". ").append(steps.get(i)).append("\n");
        }
        sb.append("\n");

        sb.append("Expected Results:\n");
        for (int i = 0; i < expectedResults.size(); i++) {
            sb.append(i + 1).append(". ").append(expectedResults.get(i)).append("\n");
        }

        return sb.toString();
    }

    public String toGherkinFormat() {
        StringBuilder sb = new StringBuilder();

        sb.append("Feature: ").append(title).append("\n");
        sb.append("  As a user\n");
        sb.append("  I want to interact with the application\n");
        sb.append("  So that I can accomplish my tasks\n\n");

        sb.append("  Scenario: ").append(title).append("\n");

        if (precondition != null && !precondition.isEmpty()) {
            sb.append("    Given ").append(precondition).append("\n");
        }

        for (String step : steps) {
            sb.append("    When ").append(step).append("\n");
        }

        for (String expected : expectedResults) {
            sb.append("    Then ").append(expected).append("\n");
        }

        return sb.toString();
    }

    public String toPlaywrightScript() {
        StringBuilder script = new StringBuilder();

        script.append("// Generated by AutomationScriptCreator\n");
        script.append("// Test Case: ").append(title).append("\n");
        script.append("// ID: ").append(id).append("\n");
        script.append("// Priority: ").append(priority).append("\n\n");

        script.append("const { test, expect } = require('@playwright/test');\n\n");

        script.append("test('").append(sanitizeForFunctionName(title)).append("', async ({ page }) => {\n");

        // Add precondition if it's a navigation
        if (precondition != null && precondition.contains("http")) {
            String url = extractUrl(precondition);
            if (url != null) {
                script.append("  // Navigate to page\n");
                script.append("  await page.goto('").append(url).append("');\n");
                script.append("  await expect(page).toHaveTitle(/.*/);\n\n");
            }
        }

        // Convert steps to Playwright code
        if (steps != null && !steps.isEmpty()) {
            script.append("  // Test Steps\n");
            for (int i = 0; i < steps.size(); i++) {
                String step = steps.get(i);
                script.append("  // Step ").append(i + 1).append(": ").append(step).append("\n");
                script.append("  ").append(convertStepToPlaywright(step)).append("\n");
            }
        }

        // Add assertions for expected results
        if (expectedResults != null && !expectedResults.isEmpty()) {
            script.append("\n  // Assertions\n");
            for (String result : expectedResults) {
                script.append("  ").append(convertResultToAssertion(result)).append("\n");
            }
        }

        script.append("});\n");
        return script.toString();
    }

    private String sanitizeForFunctionName(String input) {
        if (input == null) return "test_case";
        return input.toLowerCase()
                .replaceAll("[^a-z0-9]", "_")
                .replaceAll("_+", "_")
                .replaceAll("^_+|_+$", "");
    }

    private String extractUrl(String text) {
        if (text == null) return null;
        // Simple URL extraction
        java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("https?://[^\\s]+");
        java.util.regex.Matcher matcher = pattern.matcher(text);
        if (matcher.find()) {
            return matcher.group();
        }
        return null;
    }

    private String convertStepToPlaywright(String step) {
        if (step == null) return "// Unknown step";

        step = step.toLowerCase();

        if (step.contains("click") || step.contains("tap") || step.contains("press")) {
            return handleClickStep(step);
        } else if (step.contains("type") || step.contains("enter") || step.contains("input") || step.contains("fill")) {
            return handleTypeStep(step);
        } else if (step.contains("navigate") || step.contains("go to") || step.contains("visit")) {
            return handleNavigationStep(step);
        } else if (step.contains("hover") || step.contains("mouse over")) {
            return handleHoverStep(step);
        } else if (step.contains("select") || step.contains("choose") || step.contains("option")) {
            return handleSelectStep(step);
        } else if (step.contains("verify") || step.contains("check") || step.contains("assert")) {
            return handleVerificationStep(step);
        } else if (step.contains("wait") || step.contains("pause") || step.contains("delay")) {
            return "await page.waitForTimeout(1000);";
        } else if (step.contains("scroll")) {
            return "await page.evaluate(() => window.scrollBy(0, 500));";
        } else {
            return "// TODO: Implement step: " + step;
        }
    }

    private String handleClickStep(String step) {
        // Extract selector from step
        String selector = extractSelector(step);
        if (selector != null) {
            return "await page.click('" + selector + "');";
        }
        return "// TODO: Click action - need selector";
    }

    private String handleTypeStep(String step) {
        String selector = extractSelector(step);
        String testValue = "test@example.com"; // Default test value

        if (step.contains("email") || step.contains("username")) {
            testValue = "test@example.com";
        } else if (step.contains("password")) {
            testValue = "TestPassword123!";
        } else if (step.contains("name")) {
            testValue = "Test User";
        } else if (step.contains("phone") || step.contains("mobile")) {
            testValue = "123-456-7890";
        } else if (step.contains("address")) {
            testValue = "123 Test Street";
        }

        if (selector != null) {
            return "await page.fill('" + selector + "', '" + testValue + "');";
        }
        return "// TODO: Type action - need selector";
    }

    private String handleNavigationStep(String step) {
        String url = extractUrl(step);
        if (url != null) {
            return "await page.goto('" + url + "');";
        }
        return "// TODO: Navigation action - need URL";
    }

    private String handleHoverStep(String step) {
        String selector = extractSelector(step);
        if (selector != null) {
            return "await page.hover('" + selector + "');";
        }
        return "// TODO: Hover action - need selector";
    }

    private String handleSelectStep(String step) {
        String selector = extractSelector(step);
        if (selector != null) {
            return "await page.selectOption('" + selector + "', { label: 'Option 1' });";
        }
        return "// TODO: Select action - need selector";
    }

    private String handleVerificationStep(String step) {
        if (step.contains("visible") || step.contains("displayed")) {
            String selector = extractSelector(step);
            if (selector != null) {
                return "await expect(page.locator('" + selector + "')).toBeVisible();";
            }
        } else if (step.contains("text") || step.contains("contains")) {
            // Try to extract text to verify
            return "// TODO: Text verification - implement based on context";
        }
        return "// TODO: Verification step";
    }

    private String convertResultToAssertion(String result) {
        if (result == null) return "// Assertion";

        result = result.toLowerCase();

        if (result.contains("load") || result.contains("loaded")) {
            return "await expect(page).toHaveTitle(/.*/);";
        } else if (result.contains("visible") || result.contains("displayed")) {
            return "// TODO: Add visibility assertions for key elements";
        } else if (result.contains("error") || result.contains("fail")) {
            return "// Verify no console errors\n  const consoleErrors = [];\n  page.on('console', msg => {\n    if (msg.type() === 'error') consoleErrors.push(msg.text());\n  });\n  expect(consoleErrors).toHaveLength(0);";
        } else if (result.contains("respond") || result.contains("time")) {
            return "// Performance check - page should load\n  await expect(page).toBeTruthy();";
        } else {
            return "// Assert: " + result;
        }
    }

    private String extractSelector(String step) {
        // Simple selector extraction - in real app, you'd have more sophisticated logic
        if (step.contains("button")) {
            return "button";
        } else if (step.contains("input") || step.contains("field")) {
            return "input[type='text']";
        } else if (step.contains("link") || step.contains("a href")) {
            return "a";
        } else if (step.contains("form")) {
            return "form";
        } else if (step.contains("menu") || step.contains("nav")) {
            return "nav";
        }
        return null;
    }
}