package com.pxbtdev.service;

import com.pxbtdev.model.entity.TestCase;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.TimeUnit;

@Slf4j
@Service
public class PlaywrightRunnerService {

    @Value("${playwright.test.dir:./generated-playwright-tests}")
    private String testDir;

    @Value("${playwright.report.dir:./playwright-report}")
    private String reportDir;

    @Value("${playwright.execution.timeout:300000}")
    private long executionTimeout;

    @PostConstruct
    public void warmUp() {
        Thread.ofVirtual().name("playwright-warmup").start(() -> {
            try {
                Path dir = Paths.get(testDir);
                Files.createDirectories(dir);
                ensurePlaywrightProject(dir);
                if (!isPlaywrightInstalled(dir)) {
                    log.info("Playwright not ready — installing in background...");
                    installPlaywright(dir);
                    log.info("Playwright warm-up complete.");
                } else {
                    log.info("Playwright already installed — skipping warm-up.");
                }
            } catch (Exception e) {
                log.warn("Playwright warm-up failed (will retry on first test run): {}", e.getMessage());
            }
        });
    }

    /**
     * Generate a complete Playwright test script from test cases.
     */
    public String generatePlaywrightScript(List<TestCase> testCases, String baseUrl) {
        StringBuilder script = new StringBuilder();

        script.append("// Generated by AutomationScriptCreator\n");
        script.append("// Target: ").append(baseUrl).append("\n");
        script.append("// Generated: ").append(new java.util.Date()).append("\n\n");
        script.append("const { test, expect } = require('@playwright/test');\n\n");

        // Global timeout and base URL
        script.append("test.setTimeout(30000);\n\n");

        // Group tests by category
        Map<String, List<TestCase>> grouped = groupTestCases(testCases);

        for (Map.Entry<String, List<TestCase>> entry : grouped.entrySet()) {
            String category = entry.getKey();
            List<TestCase> group = entry.getValue();

            script.append("test.describe('").append(sanitize(category)).append("', () => {\n\n");

            for (TestCase tc : group) {
                script.append("  test('").append(sanitize(tc.getTitle())).append("', async ({ page }) => {\n");
                script.append("    // ").append(tc.getDescription() != null ? tc.getDescription() : "").append("\n");

                // Navigate to URL
                String url = tc.getTargetUrl() != null ? tc.getTargetUrl() : baseUrl;
                script.append("    await page.goto('").append(url).append("');\n");
                script.append("    await page.waitForLoadState('domcontentloaded');\n\n");

                // Generate steps
                if (tc.getSteps() != null) {
                    for (String step : tc.getSteps()) {
                        script.append("    // ").append(step).append("\n");
                        script.append(convertStepToCode(step, tc.getElementSelector())).append("\n");
                    }
                }

                // Basic assertions
                script.append("\n    // Assertions\n");
                if (tc.getExpectedResults() != null) {
                    for (String result : tc.getExpectedResults()) {
                        script.append("    // Expected: ").append(result).append("\n");
                    }
                }
                script.append("    await expect(page).not.toHaveTitle('');\n");

                script.append("  });\n\n");
            }

            script.append("});\n\n");
        }

        return script.toString();
    }

    private Map<String, List<TestCase>> groupTestCases(List<TestCase> testCases) {
        Map<String, List<TestCase>> groups = new LinkedHashMap<>();
        for (TestCase tc : testCases) {
            String category = determineCategory(tc);
            groups.computeIfAbsent(category, k -> new ArrayList<>()).add(tc);
        }
        return groups;
    }

    private String determineCategory(TestCase tc) {
        if (tc.getTags() == null)
            return "General Tests";
        List<String> tags = tc.getTags();
        if (tags.contains("smoke"))
            return "Smoke Tests";
        if (tags.contains("form"))
            return "Form Tests";
        if (tags.contains("navigation"))
            return "Navigation Tests";
        if (tags.contains("accessibility") || tags.contains("a11y"))
            return "Accessibility Tests";
        if (tags.contains("ai-enhanced"))
            return "AI-Enhanced Tests";
        if (tags.contains("validation"))
            return "Validation Tests";
        return "Element Tests";
    }

    private String convertStepToCode(String step, String elementSelector) {
        if (step == null)
            return "";
        String s = step.toLowerCase();

        if (s.contains("navigate to") || s.contains("go to")) {
            String url = extractUrl(step);
            return url != null ? "    await page.goto('" + url + "');" : "    await page.reload();";
        }
        if (s.contains("click") && elementSelector != null && !elementSelector.isEmpty()) {
            return "    await page.click(\"" + elementSelector + "\");";
        }
        if ((s.contains("fill") || s.contains("type") || s.contains("enter")) && elementSelector != null
                && !elementSelector.isEmpty()) {
            String value = extractTestValue(step);
            return "    await page.fill(\"" + elementSelector + "\", '" + value + "');";
        }
        if (s.contains("wait")) {
            return "    await page.waitForLoadState('networkidle');";
        }
        if (s.contains("verify") || s.contains("check") || s.contains("assert")) {
            return "    await expect(page.locator('body')).toBeVisible();";
        }
        if (s.contains("submit")) {
            return elementSelector != null ? "    await page.locator(\"" + elementSelector + "\").press('Enter');"
                    : "    await page.keyboard.press('Enter');";
        }
        return "    // " + step;
    }

    private String extractUrl(String text) {
        int idx = text.indexOf("http");
        if (idx >= 0) {
            String[] parts = text.substring(idx).split("\\s+");
            return parts[0].replaceAll("[',;]$", "");
        }
        return null;
    }

    private String extractTestValue(String step) {
        // Extract value in quotes
        if (step.contains("'")) {
            int s = step.indexOf("'");
            int e = step.indexOf("'", s + 1);
            if (e > s)
                return step.substring(s + 1, e);
        }
        if (step.contains("\"")) {
            int s = step.indexOf("\"");
            int e = step.indexOf("\"", s + 1);
            if (e > s)
                return step.substring(s + 1, e);
        }
        return "test value";
    }

    /**
     * Save a script to disk and run it with Playwright.
     */
    public Map<String, Object> runScript(String scriptContent, String testName) {
        log.info("Initiating Playwright test execution for: [{}]", testName);
        Map<String, Object> result = new HashMap<>();
        long startTime = System.currentTimeMillis();

        try {
            // Ensure test directory exists
            Path dir = Paths.get(testDir);
            if (!Files.exists(dir)) {
                log.info("Creating generated tests directory at: [{}]", dir.toAbsolutePath());
                Files.createDirectories(dir);
            }

            // Write package.json if missing
            ensurePlaywrightProject(dir);

            // Write test file
            String filename = testName.replaceAll("[^a-zA-Z0-9_-]", "_") + ".spec.js";
            Path testFile = dir.resolve(filename);
            log.info("Writing Playwright script content to file: [{}]", testFile.toAbsolutePath());
            Files.writeString(testFile, scriptContent);

            // Check if playwright is installed
            if (!isPlaywrightInstalled(dir)) {
                log.info("Playwright dependencies missing in [{}]. Starting installation...", dir);
                installPlaywright(dir);
            }

            // Run test
            log.info("Launching Playwright test process...");
            return executeTest(dir, filename, startTime);

        } catch (Exception e) {
            log.error("CRITICAL: Playwright execution failed for {} after {}ms: {}", 
                    testName, (System.currentTimeMillis() - startTime), e.getMessage(), e);
            result.put("success", false);
            result.put("error", e.getMessage());
            result.put("executionTime", System.currentTimeMillis() - startTime);
            return result;
        }
    }

    private void ensurePlaywrightProject(Path dir) throws IOException {
        Path packageJson = dir.resolve("package.json");
        if (!Files.exists(packageJson)) {
            String pkg = """
                    {
                      "name": "generated-playwright-tests",
                      "version": "1.0.0",
                      "scripts": {
                        "test": "playwright test"
                      },
                      "devDependencies": {
                        "@playwright/test": "^1.42.0"
                      }
                    }
                    """;
            Files.writeString(packageJson, pkg);
        }

        Path playwrightConfig = dir.resolve("playwright.config.js");
        if (!Files.exists(playwrightConfig)) {
            String config = """
                    const { defineConfig } = require('@playwright/test');
                    module.exports = defineConfig({
                      testDir: '.',
                      timeout: 30000,
                      reporter: [['html', { outputFolder: '../playwright-report', open: 'never' }], ['list']],
                      use: {
                        headless: true,
                        screenshot: 'only-on-failure',
                      },
                    });
                    """;
            Files.writeString(playwrightConfig, config);
        }
    }

    private boolean isPlaywrightInstalled(Path dir) {
        if (!Files.exists(dir.resolve("node_modules").resolve("@playwright"))) return false;
        // Also check that browser binaries are present — without them npx playwright test
        // will silently download Chromium mid-run, causing the process to hang indefinitely.
        Path browsersRoot = Paths.get(System.getProperty("user.home"), ".cache", "ms-playwright");
        if (IS_WINDOWS) {
            browsersRoot = Paths.get(System.getenv().getOrDefault("LOCALAPPDATA",
                    System.getProperty("user.home")), "ms-playwright");
        }
        try {
            if (!Files.exists(browsersRoot)) return false;
            return Files.list(browsersRoot).anyMatch(p -> p.getFileName().toString().startsWith("chromium"));
        } catch (Exception e) {
            return false;
        }
    }

    private static final boolean IS_WINDOWS =
            System.getProperty("os.name", "").toLowerCase().contains("win");

    private List<String> cmd(String... args) {
        if (IS_WINDOWS) {
            List<String> command = new ArrayList<>(List.of("cmd", "/c"));
            command.addAll(List.of(args));
            return command;
        }
        // On Linux/Mac use bash -c so the shell resolves npm/npx via the user's PATH
        return List.of("/bin/bash", "-c", String.join(" ", args));
    }

    /** Augment PATH with common Node.js install locations so npm/npx can be found. */
    private void withNodePath(ProcessBuilder pb) {
        if (IS_WINDOWS) return;
        Map<String, String> env = pb.environment();
        String existing = env.getOrDefault("PATH", "");
        String home = System.getProperty("user.home", "");
        String extra = String.join(File.pathSeparator,
                "/usr/local/bin",
                "/usr/bin",
                home + "/.nvm/versions/node/current/bin",
                home + "/.volta/bin",
                home + "/.fnm/current/bin");
        env.put("PATH", extra + File.pathSeparator + existing);
    }

    private void installPlaywright(Path dir) throws IOException, InterruptedException {
        ProcessBuilder pb = new ProcessBuilder(cmd("npm", "install", "--prefer-offline"))
                .directory(dir.toFile())
                .redirectErrorStream(true);
        withNodePath(pb);
        Process process = pb.start();
        boolean finished = process.waitFor(120, TimeUnit.SECONDS);
        if (!finished) {
            process.destroyForcibly();
            throw new RuntimeException("npm install timed out");
        }
        // Install Chromium browser binaries (can take a few minutes on first run)
        log.info("Installing Chromium browser binaries — this may take a few minutes on first run...");
        ProcessBuilder pbInstall = new ProcessBuilder(cmd("npx", "playwright", "install", "chromium"))
                .directory(dir.toFile())
                .redirectErrorStream(true);
        withNodePath(pbInstall);
        Process installProcess = pbInstall.start();
        try (BufferedReader r = new BufferedReader(new InputStreamReader(installProcess.getInputStream()))) {
            r.lines().forEach(line -> log.info("[playwright-install] {}", line));
        }
        boolean browserInstalled = installProcess.waitFor(300, TimeUnit.SECONDS);
        if (!browserInstalled) {
            installProcess.destroyForcibly();
            throw new RuntimeException("Playwright browser install timed out after 5 minutes");
        }
        log.info("Chromium browser installation complete (exit {})", installProcess.exitValue());
    }

    private Map<String, Object> executeTest(Path dir, String filename, long startTime)
            throws IOException, InterruptedException {
        Map<String, Object> result = new HashMap<>();

        ProcessBuilder pb = new ProcessBuilder(
                cmd("npx", "playwright", "test", filename,
                "--reporter=list",
                "--output=../test-results"))
                .directory(dir.toFile())
                .redirectErrorStream(true);
        withNodePath(pb);

        Process process = pb.start();

        StringBuilder output = new StringBuilder();
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                output.append(line).append("\n");
            }
        }

        boolean finished = process.waitFor(executionTimeout, TimeUnit.MILLISECONDS);
        if (!finished) {
            process.destroyForcibly();
            result.put("success", false);
            result.put("error", "Test execution timed out");
        } else {
            int exitCode = process.exitValue();
            result.put("success", exitCode == 0);
            result.put("exitCode", exitCode);
            if (exitCode != 0) {
                log.warn("Playwright tests failed (exit code {}). Output:\n{}", exitCode, output);
            }
        }

        result.put("output", output.toString());
        result.put("executionTime", System.currentTimeMillis() - startTime);
        result.put("reportUrl", "/playwright-report/index.html");

        log.info("Test execution completed. Exit code: {}, Time: {}ms",
                result.get("exitCode"), result.get("executionTime"));
        return result;
    }

    public Map<String, Object> getStatus() {
        Map<String, Object> status = new HashMap<>();
        status.put("testDir", testDir);
        status.put("reportDir", reportDir);
        status.put("testDirExists", Files.exists(Paths.get(testDir)));
        status.put("reportExists", Files.exists(Paths.get(reportDir).resolve("index.html")));

        Path nodeModules = Paths.get(testDir).resolve("node_modules").resolve("@playwright");
        status.put("playwrightInstalled", Files.exists(nodeModules));

        return status;
    }

    private String sanitize(String input) {
        if (input == null)
            return "";
        return input.replace("'", "\\'").replace("\n", " ");
    }
}