package com.pxbtdev.component;

import com.pxbtdev.model.entity.UserAction;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class PlaywrightGenerator {

    public String generateScript(List<UserAction> actions, boolean includeAssertions, boolean addComments) {
        if (actions == null || actions.isEmpty()) {
            return generateEmptyScript();
        }

        StringBuilder script = new StringBuilder();

        // Header
        script.append("// Generated by AutomationScriptCreator\n");
        script.append("// Total Actions: ").append(actions.size()).append("\n\n");

        // Import
        script.append("const { test, expect } = require('@playwright/test');\n\n");

        // Test function
        script.append("test('automated_test', async ({ page }) => {\n");

        // Add actions
        for (int i = 0; i < actions.size(); i++) {
            UserAction action = actions.get(i);

            if (addComments) {
                script.append("  // Action ").append(i + 1).append(": ")
                        .append(action.getType()).append(" on '").append(action.getSelector()).append("'\n");
            }

            script.append("  ").append(generateActionCode(action)).append("\n");
        }

        // Add assertions if requested
        if (includeAssertions) {
            script.append("\n  // Assertions\n");
            script.append("  await expect(page).toHaveTitle(/.*/);\n");
            script.append("  console.log('✅ Test completed successfully');\n");
        }

        script.append("});\n");
        return script.toString();
    }

    private String generateEmptyScript() {
        return """
            // Generated by AutomationScriptCreator
            // No actions recorded yet
            
            const { test, expect } = require('@playwright/test');
            
            test('empty_test', async ({ page }) => {
              console.log('No actions recorded for this test');
              await expect(page).toBeTruthy();
            });
            """;
    }

    private String generateActionCode(UserAction action) {
        if (action.getType() == null) {
            return "// Invalid action type";
        }

        switch (action.getType()) {
            case CLICK:
                return String.format("await page.click('%s');", escape(action.getSelector()));
            case TYPE:
                String value = action.getValue() != null ? action.getValue() : "";
                return String.format("await page.fill('%s', '%s');",
                        escape(action.getSelector()), escape(value));
            case NAVIGATE:
                String url = action.getValue() != null ? action.getValue() :
                        (action.getUrl() != null ? action.getUrl() : "");
                return String.format("await page.goto('%s');", escape(url));
            case HOVER:
                return String.format("await page.hover('%s');", escape(action.getSelector()));
            case SCROLL:
                return "await page.evaluate(() => window.scrollBy(0, 100));";
            default:
                return String.format("// %s action (not implemented)", action.getType());
        }
    }

    private String escape(String input) {
        if (input == null) return "";
        return input.replace("'", "\\'")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }
}